## Merging the pg&e data set with geographic data(city and lat/long coords)

In [2]:
import pandas as pd
import numpy as np
import os
import pprint as pp
import geopandas as gpd


# !pip install geopandas

In [24]:
!ls data

7882666-5bdc46db47d9515269ab12ed6fb2850377fd869e.zip
Bay Area Zip Codes + City Name - Sheet1.csv
CA_Counties
PGE
US-Zip-Codes-from-2013-Government-Data.csv
us-zip-code-latitude-and-longitude
us-zip-code-latitude-and-longitude.csv
us-zip-code-latitude-and-longitude.zip

In [4]:
def info(df):
    print(df.shape)
    print(df.columns)
    display(df.head())

In [30]:
full_cleaned_fn = "cleaned_data/pge-monthly-full-cleaned-by-zip_2013-2020.csv"
full_cleaned_df = pd.read_csv(full_cleaned_fn) ## ZIPCODE neds tot be string ttype to merge with latlong mapping dataframe

info(full_cleaned_df)
type(full_cleaned_df['ZIPCODE'][0])

(154283, 17)
Index(['Unnamed: 0', 'ZIPCODE', 'DATE', 'MONTH', 'YEAR', 'DAY',
       'CUSTOMERCLASS', 'COMBINED', 'TOTALCUSTOMERS', 'TOTALKWH', 'AVERAGEKWH',
       'TOTALTHERMS', 'AVERAGETHERMS', 'Calculated AVGKWH',
       'Calculated AVGTHERMS', 'AVGKWH Diff', 'AVGTHERMS Diff'],
      dtype='object')

,Unnamed: 0,ZIPCODE,DATE,MONTH,YEAR,DAY,CUSTOMERCLASS,COMBINED,TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH,TOTALTHERMS,AVERAGETHERMS,Calculated AVGKWH,Calculated AVGTHERMS,AVGKWH Diff,AVGTHERMS Diff
0,0,93101,2013-01-01,1,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0
1,1,93101,2013-02-01,2,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0
2,2,93101,2013-03-01,3,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0
3,3,93105,2013-01-01,1,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0
4,4,93105,2013-02-01,2,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0

numpy.int64

In [31]:
## this is the geographic data in a shapefile
zipcodes_to_latlong_fn = "data/US-Zip-Codes-from-2013-Government-Data.csv"
zipcodes_to_latlong_df = pd.read_csv(zipcodes_to_latlong_fn)

info(zipcodes_to_latlong_df)
type(zipcodes_to_latlong_df['ZIP'][0])

(33144, 3)
Index(['ZIP', 'LAT', 'LNG'], dtype='object')

   ZIP        LAT        LNG
0  601  18.180555 -66.749961
1  602  18.361945 -67.175597
2  603  18.455183 -67.119887
3  606  18.158345 -66.932911
4  610  18.295366 -67.125135

numpy.int64

In [32]:
pd.merge(left=full_cleaned_df, right=zipcodes_to_latlong_df, left_on="ZIPCODE", right_on='ZIP', how='inner')

,Unnamed: 0,ZIPCODE,DATE,MONTH,YEAR,DAY,CUSTOMERCLASS,COMBINED,TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH,TOTALTHERMS,AVERAGETHERMS,Calculated AVGKWH,Calculated AVGTHERMS,AVGKWH Diff,AVGTHERMS Diff,ZIP,LAT,LNG
0,0,93101,2013-01-01,1,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,93101,34.418979,-119.709166
1,1,93101,2013-02-01,2,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,93101,34.418979,-119.709166
2,2,93101,2013-03-01,3,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,93101,34.418979,-119.709166
3,4341,93101,2013-04-01,4,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,93101,34.418979,-119.709166
4,4342,93101,2013-05-01,5,2013,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,93101,34.418979,-119.709166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152176,146376,94304,2020-08-01,8,2020,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,94304,37.374707,-122.181698
152177,146377,94304,2020-09-01,9,2020,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,94304,37.374707,-122.181698
152178,150692,94304,2020-10-01,10,2020,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,94304,37.374707,-122.181698
152179,150693,94304,2020-11-01,11,2020,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,94304,37.374707,-122.181698
152180,150694,94304,2020-12-01,12,2020,1,Elec- Residential,Y,0,0,0,0,0,0.0,0.0,0.0,0.0,94304,37.374707,-122.181698

In [17]:
cities_zips = zipcodes_to_latlong_gdf['zip'].unique()
pge_zips = full_cleaned_df['ZIPCODE'].unique()

In [33]:
for z in pge_zips:
    if z not in cities_zips:
        print(z)

93314
93619
93636
93723
93730
93737
94158
94505
94582
95391
95467
95757
95811

In [22]:
zipcodes_to_latlong_gdf[zipcodes_to_latlong_gdf['zip']=='93314']

,Unnamed: 0,ZIPCODE,DATE,MONTH,YEAR,DAY,CUSTOMERCLASS,COMBINED,TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH,TOTALTHERMS,AVERAGETHERMS,Calculated AVGKWH,Calculated AVGTHERMS,AVGKWH Diff,AVGTHERMS Diff
144,144,93314,2013-01-01,1,2013,1,Elec- Residential,N,6719,5619273,836,0,0,836.325793,0.000000,0.325793,0.000000
145,145,93314,2013-02-01,2,2013,1,Elec- Residential,N,6870,4612359,671,0,0,671.376856,0.000000,0.376856,0.000000
146,146,93314,2013-03-01,3,2013,1,Elec- Residential,N,7150,4751023,664,0,0,664.478741,0.000000,0.478741,0.000000
2628,2628,93314,2013-01-01,1,2013,1,Gas- Residential,Y,897,0,0,92317,103,0.000000,102.917503,0.000000,-0.082497
2629,2629,93314,2013-02-01,2,2013,1,Gas- Residential,Y,907,0,0,59476,66,0.000000,65.574421,0.000000,-0.425579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150105,150105,93314,2020-11-01,11,2020,1,Elec- Residential,N,9945,4695586,472,0,0,472.155455,0.000000,0.155455,0.000000
150106,150106,93314,2020-12-01,12,2020,1,Elec- Residential,N,9962,6407995,643,0,0,643.243827,0.000000,0.243827,0.000000
152594,152594,93314,2020-10-01,10,2020,1,Gas- Residential,Y,1490,0,0,38468,26,0.000000,25.817450,0.000000,-0.182550
152595,152595,93314,2020-11-01,11,2020,1,Gas- Residential,Y,1502,0,0,68339,45,0.000000,45.498668,0.000000,0.498668
152596,152596,93314,2020-12-01,12,2020,1,Gas- Residential,Y,1516,0,0,115788,76,0.000000,76.377309,0.000000,0.377309

# Comining with NREL Solar Radiation DB

reference: https://nsrdb.nrel.gov/data-sets/api-instructions.html

In [4]:
# Declare all variables as strings. Spaces must be replaced with '+', i.e., change 'John Smith' to 'John+Smith'.
# Define the lat, long of the location and the year
lat, lon, year = 33.2164, -97.1292, 2010
# You must request an NSRDB api key from the link above
api_key = 'mdnmypDExxImsh4gPrjBvuhkmynKP9aizbHZ0ekn'
# Set the attributes to extract (e.g., dhi, ghi, etc.), separated by commas.
attributes = 'ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle'
# Choose year of data
year = '2010'
# Set leap year to true or false. True will return leap day data if present, false will not.
leap_year = 'false'
# Set time interval in minutes, i.e., '30' is half hour intervals. Valid intervals are 30 & 60.
interval = '30'
# Specify Coordinated Universal Time (UTC), 'true' will use UTC, 'false' will use the local time zone of the data.
# NOTE: In order to use the NSRDB data in SAM, you must specify UTC as 'false'. SAM requires the data to be in the
# local time zone.
utc = 'false'
# Your full name, use '+' instead of spaces.
your_name = 'Justin Wong'
# Your reason for using the NSRDB.
reason_for_use = 'Educational'
# Your affiliation
your_affiliation = 'UC Berkeley'
# Your email address
your_email = 'justinryanwong@berkeley.edu'
# Please join our mailing list so we can keep you up-to-date on new developments.
mailing_list = 'true'

# Declare url string
url = 'https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}'.format(year=year, lat=lat, lon=lon, leap=leap_year, interval=interval, utc=utc, name=your_name, email=your_email, mailing_list=mailing_list, affiliation=your_affiliation, reason=reason_for_use, api=api_key, attr=attributes)
# Return just the first 2 lines to get metadata:
info = pd.read_csv(url, nrows=1)
# See metadata for specified properties, e.g., timezone and elevation
timezone, elevation = info['Local Time Zone'], info['Elevation']

In [5]:
# View metadata
info

,Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,...,Cloud Type 11,Cloud Type 12,Fill Flag 0,Fill Flag 1,Fill Flag 2,Fill Flag 3,Fill Flag 4,Fill Flag 5,Surface Albedo Units,Version
0,NSRDB,693763,-,-,-,33.21,-97.14,-6,203,-6,...,Dust,Smoke,NaN,Missing Image,Low Irradiance,Exceeds Clearsky,Missing CLoud Properties,Rayleigh Violation,NaN,3.0.6

In [9]:
# Return all but first 2 lines of csv to get data:
df = pd.read_csv('http://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}'.format(year=year, lat=lat, lon=lon, leap=leap_year, interval=interval, utc=utc, name=your_name, email=your_email, mailing_list=mailing_list, affiliation=your_affiliation, reason=reason_for_use, api=api_key, attr=attributes), skiprows=2)

# Set the time index in the pandas dataframe:
df = df.set_index(pd.date_range('1/1/{yr}'.format(yr=year), freq=interval+'Min', periods=525600/int(interval)))

# take a look
print('shape:',df.shape)
df.head()

HTTPError: HTTP Error 400: Bad Request